version: "3.9"  # optional since v1.27.0
services:
    client:
        build: './client'
        ports:
            - "3000:3000"
    server:
        build: './server'
        ports: 
            - "8000:8000"
